spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: clientSecret